name: Windows Qt QMake Release

on:
  push:
    branches:
      - main

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for semantic-release

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-qt6-base
            mingw-w64-ucrt-x86_64-qt6-tools
            mingw-w64-ucrt-x86_64-openssl
            mingw-w64-ucrt-x86_64-nodejs
            zip
          
      - name: Install semantic-release
        shell: bash
        run: |
          export PATH="/d/a/_temp/msys64/ucrt64/bin:$PATH"
          npm install -g semantic-release @semantic-release/release-notes-generator @semantic-release/github @semantic-release/changelog @semantic-release/exec @semantic-release/commit-analyzer

      - name: Run semantic-release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export PATH="/d/a/_temp/msys64/ucrt64/bin:$PATH"
          npx semantic-release
